export const cities = [
  { label: "Islamabad" },
  { label: "Punjab Cities", isDisabled: true },
  { label: "Ahmed Nager Chatha" },
  { label: "Ahmadpur East" },
  { label: "Ali Khan Abad" },
  { label: "Alipur" },
  { label: "Arifwala" },
  { label: "Attock" },
  { label: "Bhera" },
  { label: "Bhalwal" },
  { label: "Bahawalnagar" },
  { label: "Bahawalpur" },
  { label: "Bhakkar" },
  { label: "Burewala" },
  { label: "Chillianwala" },
  { label: "Chakwal" },
  { label: "Chichawatni" },
  { label: "Chiniot" },
  { label: "Chishtian" },
  { label: "Daska" },
  { label: "Darya Khan" },
  { label: "Dera Ghazi Khan" },
  { label: "Dhaular" },
  { label: "Dina" },
  { label: "Dinga" },
  { label: "Dipalpur" },
  { label: "Faisalabad" },
  { label: "Ferozewala" },
  { label: "Fateh Jang" },
  { label: "Ghakhar Mandi" },
  { label: "Gojra" },
  { label: "Gujranwala" },
  { label: "Gujrat" },
  { label: "Gujar Khan" },
  { label: "Hafizabad" },
  { label: "Haroonabad" },
  { label: "Hasilpur" },
  { label: "Haveli Lakha" },
  { label: "Jatoi" },
  { label: "Jalalpur" },
  { label: "Jattan" },
  { label: "Jampur" },
  { label: "Jaranwala" },
  { label: "Jhang" },
  { label: "Jhelum" },
  { label: "Kalabagh" },
  { label: "Karor Lal Esan" },
  { label: "Kasur" },
  { label: "Kamalia" },
  { label: "Kamoke" },
  { label: "Khanewal" },
  { label: "Khanpur" },
  { label: "Kharian" },
  { label: "Khushab" },
  { label: "Kot Addu" },
  { label: "Jauharabad" },
  { label: "Lahore" },
  { label: "Lalamusa" },
  { label: "Layyah" },
  { label: "Liaquat Pur" },
  { label: "Lodhran" },
  { label: "Malakwal" },
  { label: "Mamoori" },
  { label: "Mailsi" },
  { label: "Mandi Bahauddin" },
  { label: "Mian Channu" },
  { label: "Mianwali" },
  { label: "Multan" },
  { label: "Murree" },
  { label: "Muridke" },
  { label: "Mianwali Bangla" },
  { label: "Muzaffargarh" },
  { label: "Narowal" },
  { label: "Nankana Sahib" },
  { label: "Okara" },
  { label: "Renala Khurd" },
  { label: "Pakpattan" },
  { label: "Pattoki" },
  { label: "Pir Mahal" },
  { label: "Qaimpur" },
  { label: "Qila Didar Singh" },
  { label: "Rabwah" },
  { label: "Raiwind" },
  { label: "Rajanpur" },
  { label: "Rahim Yar Khan" },
  { label: "Rawalpindi" },
  { label: "Sadiqabad" },
  { label: "Safdarabad" },
  { label: "Sahiwal" },
  { label: "Sangla Hill" },
  { label: "Sarai Alamgir" },
  { label: "Sargodha" },
  { label: "Shakargarh" },
  { label: "Sheikhupura" },
  { label: "Sialkot" },
  { label: "Sohawa" },
  { label: "Soianwala" },
  { label: "Siranwali" },
  { label: "Talagang" },
  { label: "Taxila" },
  { label: "Toba Tek Singh" },
  { label: "Vehari" },
  { label: "Wah Cantonment" },
  { label: "Wazirabad" },
  { label: "Sindh Cities", isDisabled: true },
  { label: "Badin" },
  { label: "Bhirkan" },
  { label: "Rajo Khanani" },
  { label: "Chak" },
  { label: "Dadu" },
  { label: "Digri" },
  { label: "Diplo" },
  { label: "Dokri" },
  { label: "Ghotki" },
  { label: "Haala" },
  { label: "Hyderabad" },
  { label: "Islamkot" },
  { label: "Jacobabad" },
  { label: "Jamshoro" },
  { label: "Jungshahi" },
  { label: "Kandhkot" },
  { label: "Kandiaro" },
  { label: "Karachi" },
  { label: "Kashmore" },
  { label: "Keti Bandar" },
  { label: "Khairpur" },
  { label: "Kotri" },
  { label: "Larkana" },
  { label: "Matiari" },
  { label: "Mehar" },
  { label: "Mirpur Khas" },
  { label: "Mithani" },
  { label: "Mithi" },
  { label: "Mehrabpur" },
  { label: "Moro" },
  { label: "Nagarparkar" },
  { label: "Naudero" },
  { label: "Naushahro Feroze" },
  { label: "Naushara" },
  { label: "Nawabshah" },
  { label: "Nazimabad" },
  { label: "Qambar" },
  { label: "Qasimabad" },
  { label: "Ranipur" },
  { label: "Ratodero" },
  { label: "Rohri" },
  { label: "Sakrand" },
  { label: "Sanghar" },
  { label: "Shahbandar" },
  { label: "Shahdadkot" },
  { label: "Shahdadpur" },
  { label: "Shahpur Chakar" },
  { label: "Shikarpaur" },
  { label: "Sukkur" },
  { label: "Tangwani" },
  { label: "Tando Adam Khan" },
  { label: "Tando Allahyar" },
  { label: "Tando Muhammad Khan" },
  { label: "Thatta" },
  { label: "Umerkot" },
  { label: "Warah" },
  { label: "Khyber Cities", isDisabled: true },
  { label: "Abbottabad" },
  { label: "Adezai" },
  { label: "Alpuri" },
  { label: "Akora Khattak" },
  { label: "Ayubia" },
  { label: "Banda Daud Shah" },
  { label: "Bannu" },
  { label: "Batkhela" },
  { label: "Battagram" },
  { label: "Birote" },
  { label: "Chakdara" },
  { label: "Charsadda" },
  { label: "Chitral" },
  { label: "Daggar" },
  { label: "Dargai" },
  { label: "Darya Khan" },
  { label: "Dera Ismail Khan" },
  { label: "Doaba" },
  { label: "Dir" },
  { label: "Drosh" },
  { label: "Hangu" },
  { label: "Haripur" },
  { label: "Karak" },
  { label: "Kohat" },
  { label: "Kulachi" },
  { label: "Lakki Marwat" },
  { label: "Latamber" },
  { label: "Madyan" },
  { label: "Mansehra" },
  { label: "Mardan" },
  { label: "Mastuj" },
  { label: "Mingora" },
  { label: "Nowshera" },
  { label: "Paharpur" },
  { label: "Pabbi" },
  { label: "Peshawar" },
  { label: "Saidu Sharif" },
  { label: "Shorkot" },
  { label: "Shewa Adda" },
  { label: "Swabi" },
  { label: "Swat" },
  { label: "Tangi" },
  { label: "Tank" },
  { label: "Thall" },
  { label: "Timergara" },
  { label: "Tordher" },
  { label: "Balochistan Cities", isDisabled: true },
  { label: "Awaran" },
  { label: "Barkhan" },
  { label: "Chagai" },
  { label: "Dera Bugti" },
  { label: "Gwadar" },
  { label: "Harnai" },
  { label: "Jafarabad" },
  { label: "Jhal Magsi" },
  { label: "Kacchi" },
  { label: "Kalat" },
  { label: "Kech" },
  { label: "Kharan" },
  { label: "Khuzdar" },
  { label: "Killa Abdullah" },
  { label: "Killa Saifullah" },
  { label: "Kohlu" },
  { label: "Lasbela" },
  { label: "Lehri" },
  { label: "Loralai" },
  { label: "Mastung" },
  { label: "Musakhel" },
  { label: "Nasirabad" },
  { label: "Nushki" },
  { label: "Panjgur" },
  { label: "Pishin Valley" },
  { label: "Quetta" },
  { label: "Sherani" },
  { label: "Sibi" },
  { label: "Sohbatpur" },
  { label: "Washuk" },
  { label: "Zhob" },
  { label: "Ziarat" },
];


export const religions = ["Agnostic",
"Atheist",
"Baha'i",
"Buddhism",
"Cao Dai",
"Chinese traditional religion",
"Christianity",
"Hinduism",
"Islam",
"Jainism",
"Juche",
"Judaism",
"Neo-Paganism",
"Nonreligious",
"Rastafarianism",
"Secular",
"Shinto",
"Sikhism",
"Spiritism",
"Tenrikyo",
"Unitarian-Universalism",
"Zoroastrianism",
"primal-indigenous",
"Other" ]



export const countries = ["Afghanistan",
"Åland Islands",
"Albania",
"Algeria",
"American Samoa",
"Andorra",
"Angola",
"Anguilla",
"Antarctica",
"Antigua and Barbuda",
"Argentina",
"Armenia",
"Aruba",
"Australia",
"Austria",
"Azerbaijan",
"Bahamas",
"Bahrain",
"Bangladesh",
"Barbados",
"Belarus",
"Belgium",
"Belize",
"Benin",
"Bermuda",
"Bhutan",
"Bolivia",
"Bosnia and Herzegovina",
"Botswana",
"Bouvet Island",
"Brazil",
"British Indian Ocean Territory",
"Brunei Darussalam",
"Bulgaria",
"Burkina Faso",
"Burundi",
"Cambodia",
"Cameroon",
"Canada",
"Cape Verde",
"Cayman Islands",
"Central African Republic",
"Chad",
"Chile",
"China",
"Christmas Island",
"Cocos (Keeling) Islands",
"Colombia",
"Comoros",
"Congo",
"Congo, The Democratic Republic of The",
"Cook Islands",
"Costa Rica",
"Cote D'ivoire",
"Croatia",
"Cuba",
"Cyprus",
"Czech Republic",
"Denmark",
"Djibouti",
"Dominica",
"Dominican Republic",
"Ecuador",
"Egypt",
"El Salvador",
"Equatorial Guinea",
"Eritrea",
"Estonia",
"Ethiopia",
"Falkland Islands (Malvinas)",
"Faroe Islands",
"Fiji",
"Finland",
"France",
"French Guiana",
"French Polynesia",
"French Southern Territories",
"Gabon",
"Gambia",
"Georgia",
"Germany",
"Ghana",
"Gibraltar",
"Greece",
"Greenland",
"Grenada",
"Guadeloupe",
"Guam",
"Guatemala",
"Guernsey",
"Guinea",
"Guinea-bissau",
"Guyana",
"Haiti",
"Heard Island and Mcdonald Islands",
"Holy See (Vatican City State)",
"Honduras",
"Hong Kong",
"Hungary",
"Iceland",
"India",
"Indonesia",
"Iran, Islamic Republic of",
"Iraq",
"Ireland",
"Isle of Man",
"Israel",
"Italy",
"Jamaica",
"Japan",
"Jersey",
"Jordan",
"Kazakhstan",
"Kenya",
"Kiribati",
"Korea, Democratic People's Republic of",
"Korea, Republic of",
"Kuwait",
"Kyrgyzstan",
"Lao People's Democratic Republic",
"Latvia",
"Lebanon",
"Lesotho",
"Liberia",
"Libyan Arab Jamahiriya",
"Liechtenstein",
"Lithuania",
"Luxembourg",
"Macao",
"Macedonia, The Former Yugoslav Republic of",
"Madagascar",
"Malawi",
"Malaysia",
"Maldives",
"Mali",
"Malta",
"Marshall Islands",
"Martinique",
"Mauritania",
"Mauritius",
"Mayotte",
"Mexico",
"Micronesia, Federated States of",
"Moldova, Republic of",
"Monaco",
"Mongolia",
"Montenegro",
"Montserrat",
"Morocco",
"Mozambique",
"Myanmar",
"Namibia",
"Nauru",
"Nepal",
"Netherlands",
"Netherlands Antilles",
"New Caledonia",
"New Zealand",
"Nicaragua",
"Niger",
"Nigeria",
"Niue",
"Norfolk Island",
"Northern Mariana Islands",
"Norway",
"Oman",
"Pakistan",
"Palau",
"Palestinian Territory, Occupied",
"Panama",
"Papua New Guinea",
"Paraguay",
"Peru",
"Philippines",
"Pitcairn",
"Poland",
"Portugal",
"Puerto Rico",
"Qatar",
"Reunion",
"Romania",
"Russian Federation",
"Rwanda",
"Saint Helena",
"Saint Kitts and Nevis",
"Saint Lucia",
"Saint Pierre and Miquelon",
"Saint Vincent and The Grenadines",
"Samoa",
"San Marino",
"Sao Tome and Principe",
"Saudi Arabia",
"Senegal",
"Serbia",
"Seychelles",
"Sierra Leone",
"Singapore",
"Slovakia",
"Slovenia",
"Solomon Islands",
"Somalia",
"South Africa",
"South Georgia and The South Sandwich Islands",
"Spain",
"Sri Lanka",
"Sudan",
"Suriname",
"Svalbard and Jan Mayen",
"Swaziland",
"Sweden",
"Switzerland",
"Syrian Arab Republic",
"Taiwan",
"Tajikistan",
"Tanzania, United Republic of",
"Thailand",
"Timor-leste",
"Togo",
"Tokelau",
"Tonga",
"Trinidad and Tobago",
"Tunisia",
"Turkey",
"Turkmenistan",
"Turks and Caicos Islands",
"Tuvalu",
"Uganda",
"Ukraine",
"United Arab Emirates",
"United Kingdom",
"United States",
"United States Minor Outlying Islands",
"Uruguay",
"Uzbekistan",
"Vanuatu",
"Venezuela",
"Viet Nam",
"Virgin Islands, British",
"Virgin Islands, U.S.",
"Wallis and Futuna",
"Western Sahara",
"Yemen",
"Zambia",
"Zimbabwe"]

export const provinceWithCity = [ 
    {province :"Azaad Kashmir",city:['BAGH','BHIMBER','HATTIAN BALA','HAVELI','KOTLI','MIRPUR','MUZZAFARABAD','NEELUM VALLEY','RAWALAKOT','SUDHANOTI']},
    {province :"Balochistan",city:['Quetta','Turbat','Khuzdar','Hub','Chaman','Gwadar','Dera Allah Yar','Usta Mohammad','Sui','Sibi','Loralai','Tump','Nushki','Zhob','Kharan','Chitkan','Khanozai']},
    {province :"Fata",city:['Jamrūd','Landi Kotal','Sadda']},
    {province :"Gilgit Baltistan",city:['Gilgit','Skardu','Khaplu','Dambudas','Tolti','Eidghah','Shigar','Nagarkhas','Ishkoman','Juglot']
},
    {province :"Islamabad",city:['Rawalpindi Pakistan','Kahuta Pakistan','Wah Pakistan','Haripur Pakistan','Murree Pakistan']},
    {province :"Khyber Pakhtunkhwa",city:['Karak','Kohat','Kulachi','Lakki Marwat','Latamber','Madyan','Mansehra','Mardan','Mastuj','Mingora','Nowshera','Paharpur','Pabbi','Peshawar','Saidu Sharif','Shorkot','Shewa Adda','Swabi','Swat','Tangi','Tank','Thall','Timergara','Tordher']
},
    {province :"Punjab",city:['Ahmadpur East','Ahmed Nager Chatha','Ali Khan Abad','Alipur','Arifwala','Attock','Bhera','Bhalwal','Bahawalnagar','Bahawalpur','Bhakkar','Burewala','Chillianwala','Chakwal','Chichawatni','Chiniot','Chishtian','Daska','Darya Khan','Dera Ghazi Khan','Dhaular','Dina','Dinga','Dipalpur','Faisalabad','Fateh Jang','Ghakhar Mandi','Gojra','Gujranwala','Gujrat','Gujar Khan','Hafizabad','Haroonabad','Hasilpur','Haveli Lakha','Jalalpur Jattan','Jampur','Jaranwala','Jhang','Jhelum','Kalabagh','Karor Lal Esan','Kasur','Kamalia','Kāmoke','Khanewal','Khanpur','Kharian','Khushab','Kot Adu','Jauharabad','Lahore','Lalamusa','Layyah','Liaquat Pur','Lodhran','Malakwal','Mamoori','Mailsi','Mandi Bahauddin','Mian Channu','Mianwali','Multan','Murree','Muridke','Mianwali Bangla','Muzaffargarh','Narowal','Okara','Renala Khurd','Pakpattan','Pattoki','Pir Mahal','Qaimpur','Qila Didar Singh','Rabwah','Raiwind','Rajanpur','Rahim Yar Khan','Rawalpindi','Sadiqabad','Safdarabad','Sahiwal','Sangla Hill','Sarai Alamgir','Sargodha','Shakargarh','Sheikhupura','Sialkot','Sohawa','Soianwala','Siranwali','Talagang','Taxila','Toba Tek Singh','Vehari','Wah Cantonment','Wazirabad']
},
    {province :"Sindh",city:['Badin','Bhirkan','Rajo Khanani','Chak','Dadu','Digri','Diplo','Dokri','Ghotki','Haala','Hyderabad','Islamkot','Jacobabad','Jamshoro','Jungshahi','Kandhkot','Kandiaro','Karachi','Kashmore','Keti Bandar','Khairpur','Kotri','Larkana','Matiari','Mehar','Mirpur Khas','Mithani','Mithi','Mehrabpur','Moro','Nagarparkar','Naudero','Naushahro Feroze','Naushara','Nawabshah','Nazimabad','Qambar','Qasimabad','Ranipur','Ratodero','Rohri','Sakrand','Sanghar','Shahbandar','Shahdadkot','Shahdadpur','Shahpur Chakar','Shikarpaur','Sukkur','Tangwani','Tando Adam Khan','Tando Allahyar','Tando Muhammad Khan','Thatta','Umerkot','Warah']}
]
